# Generated by Django 4.1.13 on 2024-10-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="testmodel",
            table="test_model",
        ),
    ]
