# Generated by Django 4.1.13 on 2024-10-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_testmodel_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="testmodel",
            table=None,
        ),
    ]
