# Generated by Django 4.1.13 on 2024-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_testmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
