# Generated by Django 4.1.13 on 2024-10-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_testmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
