# Generated by Django 4.1.13 on 2024-10-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_remove_testmodel_id_testmodel__id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="_id",
        ),
        migrations.AddField(
            model_name="testmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
