# Generated by Django 4.1.13 on 2024-10-17 14:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_pollmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollmodel",
            name="author",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="pollmodel",
            name="choices",
            field=djongo.models.fields.JSONField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="pollmodel",
            name="datePosted",
            field=models.IntegerField(editable=False),
        ),
    ]
