# Generated by Django 4.1.13 on 2024-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_alter_pollmodel_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollmodel",
            name="author",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="pollmodel",
            name="datePosted",
            field=models.IntegerField(),
        ),
    ]
