# Generated by Django 4.1.13 on 2024-10-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_pollmodel_author_alter_pollmodel_dateposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='datePosted',
            field=models.CharField(max_length=500),
        ),
    ]
