# Generated by Django 4.1.13 on 2024-10-21 20:48

import django.contrib.postgres.fields
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_alter_pollmodel_dateposted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollmodel",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=djongo.models.fields.JSONField(), size=None
            ),
        ),
    ]
