# Generated by Django 4.1.13 on 2024-10-22 02:39

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_alter_pollmodel_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollmodel",
            name="voters",
            field=djongo.models.fields.JSONField(default=0),
            preserve_default=False,
        ),
    ]
